### test
GET http://localhost:3000/test

### signup
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name":"beni",
    "email":"beni@example.com",
    "password":"12345"
}

### login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"beni@example.com",
    "password":"12345",
    "deviceDetails":"Chrome 112"
}

### auth
POST http://localhost:3000/auth
Content-Type: application/json

### end connection for all
DELETE http://localhost:3000/user/endConnectionForAll
Content-Type: application/json

### end connection 
DELETE http://localhost:3000/user/endConnection
Content-Type: application/json

{
    "refreshId":"648ec7f421944bf83f333ce7"
}
